# Generated by Django 2.0.2 on 2018-02-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('questionnaires_cnt', models.IntegerField(default=4)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('is_active', models.BooleanField(default=False)),
                ('lecture_num', models.IntegerField(default=0)),
                ('question_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Question')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Student')),
            ],
        ),
    ]
