# Generated by Django 2.0.2 on 2018-03-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180301_1157'),
        ('votes', '0003_remove_question_lecture_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course'),
        ),
    ]
