# Generated by Django 2.0.2 on 2018-03-09 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_response_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 3, 10, 40, 373045, tzinfo=utc)),
        ),
    ]
