# Generated by Django 2.0.2 on 2018-03-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20180309_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
