# Generated by Django 2.0.2 on 2018-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('class_num', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
            ],
        ),
    ]
