# Generated by Django 2.0.2 on 2018-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_token',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
