# Generated by Django 2.0.2 on 2018-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_token',
            field=models.CharField(default='0', max_length=15, null=True, unique=True),
        ),
    ]
