# Generated by Django 2.0.2 on 2018-03-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='roster_filename',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
