# Generated by Django 2.0.2 on 2018-03-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_roster_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='roster_filename',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
