# Generated by Django 2.0.2 on 2018-02-22 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_text', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_text_korean', models.CharField(max_length=20)),
                ('name_text_english', models.CharField(max_length=30)),
                ('class_num', models.IntegerField(default=0)),
                ('major_text', models.CharField(max_length=30)),
                ('grade', models.IntegerField(default=0)),
                ('prev_gpa', models.FloatField(default=0)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
