# Generated by Django 2.0.2 on 2018-02-23 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0004_auto_20180222_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id_text', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_text_korean', models.CharField(max_length=20)),
                ('name_text_english', models.CharField(max_length=30)),
                ('class_num', models.IntegerField(default=0)),
                ('position_text', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
