# Generated by Django 2.0.2 on 2018-02-28 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_active'),
        ('roster', '0006_auto_20180227_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
