# Generated by Django 2.0.2 on 2018-02-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_active'),
        ('roster', '0007_student_enrolled_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_course',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_course',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
