# Generated by Django 2.0.2 on 2018-03-02 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0008_auto_20180228_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id_text', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
