# Generated by Django 2.0.2 on 2018-03-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='temp_password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
