# Generated by Django 2.0.2 on 2018-03-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_student_is_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
