# Generated by Django 2.0.2 on 2018-03-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_auto_20180302_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_num',
            field=models.IntegerField(default=0),
        ),
    ]
