# Generated by Django 2.0.2 on 2018-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_student_group_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='icampus_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
