# Generated by Django 2.0.2 on 2018-03-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_student_icampus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='icampus_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
