# Generated by Django 2.0.2 on 2018-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_auto_20180305_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='icampus_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
